//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Kontakt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontakt()
        {
            this.MailAdresas = new HashSet<MailAdresa>();
            this.Telefons = new HashSet<Telefon>();
        }

        [DisplayName("Ime:")]
        [Required(ErrorMessage = "Molimo vas unesite ime kontakta.")]
        public string Ime { get; set; }


        [DisplayName("Prezime:")]
        [Required(ErrorMessage = "Molimo vas unesite prezime kontakta.")]
        public string Prezime { get; set; }


        [DisplayName("Radno mesto:")]
        [Required(ErrorMessage = "Molimo vas unesite radno mesto kontakta.")]
        public string RadnoMesto { get; set; }


        [DisplayName("Škola ID:")]
        public int SkolaID { get; set; }

        [DisplayName("Kontakt ID:")]
        public int KontaktID { get; set; }
    
        public virtual Skola Skola { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailAdresa> MailAdresas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Telefon> Telefons { get; set; }
    }
}
