//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class MailAdresa
    {

        [DisplayName("Adresa:")]
        [Required(ErrorMessage = "Molimo vas unesite Email adresu.")]
        public string Adresa { get; set; }
 

        [DisplayName("Tip:")]
        [Required(ErrorMessage = "Molimo vas unesite tip.")]
        public string OznakaTipaMail { get; set; }
      

        [DisplayName("Kontakt ID:")]
        public int KontaktID { get; set; }
 

        public virtual Kontakt Kontakt { get; set; }
    }
}
