//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjekatFinalni.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Skola
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Skola()
        {
            this.Kontakts = new HashSet<Kontakt>();
        }
        [DisplayName("Škola ID:")]
        public int SkolaID { get; set; }

        [DisplayName("Naziv škole:")]
        [Required(ErrorMessage = "Molimo vas unesite naziv škole.")]
        public string NazivSkole { get; set; }


        [DisplayName("Adresa registracije:")]
        [Required(ErrorMessage = "Molimo vas unesite adresu registracije.")]
        public string AdresaRegistracije { get; set; }


        [DisplayName("Opština:")]
        [Required(ErrorMessage = "Molimo vas unesite ime opštine.")]
        public string Opstina { get; set; }


        [DisplayName("Poštanski broj:")]
        [Required(ErrorMessage = "Molimo vas unesite poštanski broj.")]
        public Nullable<int> PostanskiBroj { get; set; }


        [DisplayName("Matièni broj škole:")]
        [Required(ErrorMessage = "Molimo vas unesite matièni broj škole")]
        public string MaticniBrojSkole { get; set; }


        [DisplayName("PIB:")]
        [Required(ErrorMessage = "Molimo vas unesite PIB.")]
        public string PIB { get; set; }


        [DisplayName("Broj raèuna škole:")]
        [Required(ErrorMessage = "Molimo vas unesite broj raèuna škole.")]
        public string BrojRacunaSkole { get; set; }


        [DisplayName("Web stranica:")]
        public string WebStranica { get; set; }


        [DisplayName("Beleška:")]
        public string Beleska { get; set; }

        [DisplayName("Peèat:")]
        public string Fotografija { get; set; }

        public HttpPostedFileBase SlikaFajl { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kontakt> Kontakts { get; set; }
    }
}
